export const initialRecords = [
  {
    id: 'TXN001',
    date: '2025-07-01',
    type: 'income',
    category: 'Tuition Fee',
    person: 'Alice Perera',
    role: 'Student',
    className: 'Advanced Mathematics',
    amount: 5000,
    status: 'Paid',
  },
  {
    id: 'TXN002',
    date: '2025-07-01',
    type: 'outcome',
    category: 'Teacher Salary',
    person: 'Mr. Silva',
    role: 'Teacher',
    className: 'Advanced Mathematics',
    amount: 3000,
    status: 'Paid',
  },
  {
    id: 'TXN003',
    date: '2025-07-01',
    type: 'income',
    category: 'Tuition Fee',
    person: 'Hirusha Perera',
    role: 'Teacher',
    className: 'Advanced Mathematics',
    amount: 5000,
    status: 'Paid',
  },
  {
    id: 'TXN004',
    date: '2025-07-01',
    type: 'outcome',
    category: 'Cleaner Salary',
    person: 'Kumara',
    role: 'Cleaner',
    className: '-',
    amount: 500,
    status: 'Paid',
  },
  {
    id: 'TXN005',
    date: '2025-07-02',
    type: 'income',
    category: 'Exam Fee',
    person: 'Bob Silva',
    role: 'Student',
    className: 'Physics Fundamentals',
    amount: 2000,
    status: 'Pending',
  },
  {
    id: 'TXN006',
    date: '2025-07-02',
    type: 'outcome',
    category: 'Cashier Salary',
    person: 'Ms. Perera',
    role: 'Cashier',
    className: '-',
    amount: 1200,
    status: 'Paid',
  },
]; 